// src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
    <div class="app-container">
      <header class="app-header">
        <h1>User Settings</h1>
      </header>
      <main class="app-main">
        <router-outlet></router-outlet>
      </main>
    </div>
  `,
  styles: [`
    .app-container {
      min-height: 100vh;
    }
    .app-header {
      background-color: #2c3e50;
      color: white;
      padding: 1rem 2rem;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }
    .app-header h1 {
      margin: 0;
      font-size: 1.5rem;
    }
    .app-main {
      max-width: 1200px;
      margin: 0 auto;
      padding: 2rem;
    }
  `]
})
export class AppComponent {
  title = 'user-settings-app';
}

// src/App.svelte
<script>
  import FeedbackForm from './components/FeedbackForm.svelte';
</script>

<main>
  <div class="container">
    <h1>Feedback Form</h1>
    <p class="subtitle">We'd love to hear your feedback!</p>
    <FeedbackForm />
  </div>
</main>

<style>
  main {
    min-height: 100vh;
    padding: 2rem;
    background-color: #f5f5f5;
  }

  .container {
    max-width: 800px;
    margin: 0 auto;
  }

  h1 {
    color: #2c3e50;
    text-align: center;
    margin-bottom: 0.5rem;
  }

  .subtitle {
    color: #7f8c8d;
    text-align: center;
    margin-bottom: 2rem;
  }
</style>
